import { HydratedDocument, SchemaTypes, Types } from 'mongoose';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

export type SupportMessageDocument = HydratedDocument<SupportMessage>;

export enum SupportMessageDirection {
  INCOMING = 'incoming',
  OUTGOING = 'outgoing',
}

export enum SupportMessageType {
  TEXT = 'text',
  IMAGE = 'image',
  AUDIO = 'audio',
  VIDEO = 'video',
  DOCUMENT = 'document',
  STICKER = 'sticker',
  LOCATION = 'location',
}

export enum SupportMessageStatus {
  PENDING = 'pending',
  SENT = 'sent',
  DELIVERED = 'delivered',
  READ = 'read',
  FAILED = 'failed',
}

@Schema({
  timestamps: true,
  collection: 'support_messages',
})
export class SupportMessage {
  @Prop({ type: SchemaTypes.ObjectId, ref: 'Tenant', required: true, index: true })
  companyId: Types.ObjectId;

  @Prop({ type: SchemaTypes.ObjectId, ref: 'SupportConversation', required: true, index: true })
  conversationId: Types.ObjectId;

  @Prop({ type: SchemaTypes.ObjectId, ref: 'WhatsappSession', default: null })
  whatsappSessionId: Types.ObjectId | null;

  @Prop({ type: String, default: null })
  whatsappMessageId: string | null;

  @Prop({ required: true, enum: Object.values(SupportMessageDirection) })
  direction: SupportMessageDirection;

  @Prop({ required: true, enum: Object.values(SupportMessageType) })
  messageType: SupportMessageType;

  @Prop({ default: '' })
  body: string;

  @Prop({ type: String, default: null })
  mediaUrl: string | null;

  @Prop({ type: String, default: null })
  mediaMimeType: string | null;

  @Prop({ type: String, default: null })
  mediaFileName: string | null;

  @Prop({ type: SchemaTypes.ObjectId, ref: 'User', default: null })
  sentByUserId: Types.ObjectId | null;

  @Prop({ type: String, default: null })
  sentByUserNameSnapshot: string | null;

  @Prop({
    required: true,
    enum: Object.values(SupportMessageStatus),
    default: SupportMessageStatus.PENDING,
  })
  status: SupportMessageStatus;

  @Prop({ type: String, default: null })
  errorMessage: string | null;

  @Prop({ type: Date, default: null })
  providerTimestamp: Date | null;

  /**
   * Idempotency key generated by the dashboard for each send. A retried or doubled
   * request with the same key returns the original message instead of sending again.
   */
  @Prop({ type: String, default: null })
  clientMessageId: string | null;

  /**
   * True once WhatsApp's own echo of an agent-sent message has been matched to this
   * record. Until then an echo/sync with the same body is attached here instead of being
   * stored as a second "sent from phone" message.
   */
  @Prop({ type: Boolean, default: false })
  providerEchoMatched: boolean;

  @Prop({ type: Boolean, default: false })
  isEdited: boolean;

  @Prop({ type: Date, default: null })
  editedAt: Date | null;

  /** First version of the text, kept when the customer edits the message. */
  @Prop({ type: String, default: null })
  originalBody: string | null;

  /** For AI replies: the incoming message that triggered it (one reply per trigger). */
  @Prop({ type: String, default: null })
  aiTriggerMessageId: string | null;
}

export const SupportMessageSchema = SchemaFactory.createForClass(SupportMessage);

SupportMessageSchema.index(
  { companyId: 1, clientMessageId: 1 },
  {
    unique: true,
    partialFilterExpression: { clientMessageId: { $type: 'string' } },
    name: 'support_message_company_client_message_id',
  },
);

SupportMessageSchema.index(
  { companyId: 1, aiTriggerMessageId: 1 },
  {
    unique: true,
    partialFilterExpression: { aiTriggerMessageId: { $type: 'string' } },
    name: 'support_message_company_ai_trigger',
  },
);

SupportMessageSchema.index(
  { conversationId: 1, createdAt: 1 },
  { name: 'support_message_conversation_created' },
);

SupportMessageSchema.index(
  { companyId: 1, whatsappMessageId: 1 },
  {
    unique: true,
    partialFilterExpression: { whatsappMessageId: { $type: 'string' } },
    name: 'support_message_company_whatsapp_message_v2',
  },
);
